version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker logout
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker-compose -f docker-compose-build.yaml build --parallel
            docker-compose -f docker-compose-build.yaml push